carto:
  jshead:
    - js/d3.v3.min.js
    - js/topojson.v1.minjs
    - js/colorbrewer.js
    - js/cartogram.mod.js
  css:
    - css/mapstyle.css
  cdn:
    jshead:
      - js/d3.v3.min.js
      - js/topojson.v1.min.js
      - js/colorbrewer.js
      - js/cartogram.mod.js
    css:
      - css/mapstyle.css
